GET http://localhost:3000/movies/
###

POST http://localhost:3000/movies/
Content-Type: application/json



{
    "directorId":4,
    "movieName":"aa naluguru",
    "leadActor":"raajendraprasad"
}
###
GET http://localhost:3000/movies/4/

###

PUT http://localhost:3000/movies/48/
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###


DELETE http://localhost:3000/movies/48/
###


GET http://localhost:3000/directors/
###

GET http://localhost:3000/directors/1/movies/
